<?php
// Heading
$_['text_home ']    = 'Home';
$_['heading_title']    = 'Multivendor Settings';
$_['vendor_heading']    = 'Vendor settings';
$_['order_heading']    = 'Order settings';
$_['seller_product_heading']    = 'Tutor product settings';
$_['seller_review_heading']    = 'Tutor review settings';
$_['seller_contact_heading']    = 'Tutor contact settings';
$_['seller_email_heading']    = 'Tutor email templates';
$_['seller_store_heading']    = 'Tutor store options';
$_['text_hide_seller_product_tab'] = 'Use Smart Product Form';
$_['text_extension']   = 'Extensions';
$_['text_success']     = 'Success: You have modified Multivendor settings!';
$_['text_edit']        = 'Edit Multivendor Settings';
$_['text_yes']        = 'Yes';
$_['text_no']        = 'No';
$_['text_allowed_categories']        = 'Allow all categories';
$_['text_selected_categories']        = 'Allow selected categories';
$_['text_license_error']        = 'Your license key is invalid';
$_['text_store_seller_name']        = 'Tutor name';
$_['text_service_mode']        = "Service Mode";
$_['text_store_email']        = 'Store email';
$_['text_store_phone']        = 'Store phone';
$_['text_store_address']        = 'Store address';
$_['text_seller_logedin']        = 'Logged In';
$_['text_seller_general']        = 'General';
$_['text_license_key_changed'] = 'License key has been Changed. Click on Save button to save changes';
$_['text_assign_categories']        = 'Some products assign to this category please disable them then remove.';
$_["text_seller_product_template"]        = "Use Product Templates";
$_["text_pts_help"]        = "Enable help";

////////category for sing tutor product/////
$_['entry_seller_product_category'] = ' No. of categories allow for a single product';
$_['text_multiple']        = 'Multiple';
$_['text_single']        = 'Single';
$_['entry_commission'] = 'Commission (in percent per product sale)';
$_['entry_commission_status'] = 'Admin order status for commission calculation';
$_['entry_refund_status'] = 'Status of Return for refund calculation';
$_['please_select'] = '--Please Select--';
$_['error_commission_status'] = 'This field is required!';
$_['entry_seller_manage_order'] = 'Allow tutor to manage orders';//quick order
$_['entry_customer_manage_order'] = 'Allow customer to manage orders';
$_['entry_seller_approval'] = 'Tutor approval required';
$_['entry_product_approval'] = 'Product approval required';
$_['entry_product_edit_approval'] = 'Product edit approval required';
$_['entry_allow_category'] = 'Allow category for tutor';
$_['entry_become_seller'] = 'Become tutor on signup page';
$_['entry_seller_login'] = 'Show Tutor Login / Tutor Panel Link';
$_['entry_order_approval'] = 'Order approval required';
$_['entry_allow_related'] = 'Allow tutor to add related product';
$_['entry_limit_purchase'] = 'Max. number of tutor products allowed in cart';
$_['entry_allow_metals'] = 'Allow tutor to add metals product';
$_['entry_seller_review'] = 'Tutor review enabled';
$_['entry_seller_contact'] = 'Tutor contact mode';
$_['entry_license']        = 'License key';
$_['entry_seller_store']        = 'Fields to show';
$_['entry_seller_mode']        = 'Enable Service Mode';
$_['entry_seller_invoice']        = 'Invoice/shipping generated by tutor';
$_['commission_from_seller_group'] = 'Commission from tutor group';
$_['entry_shipping_commission'] = 'Shipping Commission (in percent)';
$_['Commission_invoice_footer_text'] = 'Commission Invoice Footer text';

// dash board icons
$_['entry_seller_dashboard_icon']= "Show Dashboard/Tutor Panel Icons";



// Entry
$_['entry_status']            = 'Status';
$_['entry_order_id']          = 'Order ID';
$_['entry_email_id']          = 'Email ID';
$_['please_wait']             = 'Please wait..';

// Error
$_['error_permission'] = 'Warning: You do not have permission to modify Multivendor Settings!';
$_['error_commission'] = 'Please enter valid commission!';
$_['error_product_limit'] = 'Please enter product limit!';
$_['error_process_data'] = 'License key is required!';
$_['error_order_id'] = 'Enter valid Order Id!';
$_['error_email_id'] = 'Enter valid e-mail address!';
$_['error_Enter_license_key'] ="Enter license key";
$_['allow_browse_sellers'] ="Enable Browse Tutors";

//button
$_['dont_have_lisence_key'] = 'Dont Have License Key'; 
$_['enter_license_key1'] = 'Enter License Key';
$_['button_get_license'] = 'Get License';
$_['button_submit'] = 'Submit';
$_['entry_allow_live_chat'] = 'Allow Tawk.to Live Chat';
$_['button_ok'] = 'OK';
$_['change_license_key'] = 'Change License Key';

//Configuration for subscription plan
$_['heading_subscription_plan']='Subscription Plan';
$_['enable_subscription_plans_txt']='Enable Subscription Plans';
$_['enable_subscription_price_txt']='Enable Subscription Fees';
$_['enable_joining_fees_txt'] ='Enable Joining Fees';
$_['paypal_hosted_button_id'] ="PayPal E-Mail ID";
$_['tax_name_txt'] ='Tax Name';
$_['tax_value_txt']='Tax Value(in percent)';///

//$_['reminder_one_enable_txt']='First Reminder Enable';
$_['reminder_one_days_before_to_be_sent_txt']='First Reminder ( in Days, 0 to disable )';
//$_['reminder_two_enable_txt']='Second Reminder Enable';
$_['reminder_two_days_before_to_be_sent_txt']='Second Reminder ( in Days, 0 to disable )';
//$_['reminder_three_enable_txt']='Third Reminder Enable';
$_['reminder_three_days_before_to_be_sent_txt']='Third Reminder ( in Days, 0 to disable )';
$_['grace_period_txt']='Grace Period';
//validation
$_['error_tax_value'] = 'Enter Valid Tax Value';
$_['error_tax_name'] = 'Enter Valid Tax Name';
$_['grace_period_error'] = 'Enter Valid Grace Period';
$_['reminder_one_days_error'] = 'Enter Valid Reminder Days';
$_['reminder_two_days_error'] = 'Enter Valid Reminder Days';
$_['reminder_three_days_error'] = 'Enter Valid Reminder Days';
$_['error_shipping_commission'] = 'Please enter valid shipping commission!';

//development option
$_['text_hide_user_menu']        = 'Hide User Menu for tutors';
$_['heading_development_Option'] = 'Development Option';
$_['enable_include_jquery']        = 'Include jQuery';
$_['enable_multiple_active_plan']        = 'Enable Multiple Subscription Plans';
$_['text_store_social_link']        = 'Social Links';//social link 

/////////////////Start tutor Blog setting/////////////////
$_['seller_blog_heading']    = 'Tutor Blog settings';
$_['text_sort_order']    = 'Sort order';
$_['text_create_date_order']    = 'Create date';
$_['entry_seller_sort_by']    = 'Sort by';
$_['form_error_warning'] = 'Please check form carefully ';

//navbar texts
$_['text_general'] = 'General';
$_['text_seller'] = 'Tutor';
$_['text_subscription'] = 'Subscription';
$_['text_other_settings'] = 'Other Settings';
$_['text_development'] = 'Development';
$_['entry_featured_enabled_hide_edit'] = 'Featured enabled hide edit button';
$_['entry_seller_featured_product'] = "Allow Tutor's Featured Products";
$_['entry_seller_category_featured_product'] = "Allow Tutor's Category Featured Product";
$_['text_allow_seller_to_reply_customer'] = "Allow Tutor's to reply customers";
$_['text_default_currency_for_paypal'] = "Default Currency for paypal";

//new string
$_['text_purpletreeshipping_type']    = "Shipping Type";
$_['text_purpletreeshipping']		  = "Zip Code Shipping";
$_['text_purpletreeshipping_geozone'] = "Geo Zone Shipping";
$_['entry_storepage_layout'] = "Tutor Store Page Layout";
$_['entry_allowseller_oncategory'] = "Show tutors on category page";
$_['text_allow_selleron_category'] = "Show tutors on category page";
$_['entry_allowtemplate_description'] = "Allow tutors to add template product description";
$_['text_layout_one'] = "Layout 1";
$_['text_layout_two'] = "Layout 2";
$_['entry_hide_seller_detail'] = 'Hide tutor detail on product page';
///Quick Order
$_['entry_show_seller_name'] = 'Show tutor name on product list';
$_['entry_show_seller_address'] = 'Show tutor address on product list';
$_['entry_seller_info_success'] = 'Show tutor information on order success page';
$_['entry_quick_order_tab_position'] = 'Quick order tab position';
$_['text_last'] = 'Last';
$_['text_first'] = 'First';
$_['entry_allow_order_status'] = 'Allow order status for tutor/customer';
$_['text_all'] = 'All';
/// End Quick Order
//// product view ////
$_['entry_products_view'] = 'Products View';
$_['text_list'] = "List";
$_['text_grid'] = "Grid";
//// product view ////
$_['text_normal_mode'] = "Normal Mode";
$_['text_category_mode'] = "Category Mode";
$_['text_service_mode'] = "Service Mode";
$_['entry_api_google'] = "Google API for Delivery Address";
//hyper-local popup 
$_['entry_seller_areaheading']="Hyperlocal "; 
$_['entry_header_popup']="Heading in Popup for Hyperlocal "; 
$_['entry_area_selection']="Area Selection Mandatory"; 
$_['entry_seller_area_link']="Go to Tutor Area"; 
$_['text_multiple_store']="Use domain wise stores"; 
$_['text_fix_commission']="Fixed Commission";
$_['text_hyper_delivering']           = 'Delivering to';
$_['entry_temp_prod_price_list'] = 'Show Tutor template product price list on product page';
$_['entry_hyperlocal_select_type'] = 'Area Display';
$_['entry_hyperlocal_select_area'] = 'Dropdown';
$_['entry_hyperlocal_search_area'] = 'Text box with suggestion';
$_['entry_hyperlocal_text_box'] = 'Text box';
$_['text_seller_reg_settings'] = 'Registration';
$_['text_hide_seller_reg_field'] = 'Hide Tutor Registraion Field';
$_['text_confirm_password'] = 'Password Confirm';
$_['text_agree'] = 'Agree policy';
$_['text_personal_details'] = 'Personal details';
$_['text_seller_information'] = 'Tutor Information';
$_['text_payment_details'] = 'Payment Details';
// hide customer detail
$_['entry_hide_customer_detail'] = 'Hide customer details from tutor';
$_['text_seller_ac_terms'] = 'Tutor		 Account Terms';
$_['text_none'] = 'None';
